[general]
live_config_reload = true
import = ["~/.config/alacritty/themes/tokyonight_night.toml"]

[colors]
draw_bold_text_with_bright_colors = true

[cursor]
style = "underline"

[env]
TERM = "xterm-256color"

[font]
size = 12.0

[font.normal]
family = "IosevkaTerm Nerd Font"
style = "Regular"

[font.bold]
family = "IosevkaTerm Nerd Font"
style = "Bold"

[font.italic]
family = "IosevkaTerm Nerd Font"
style = "Oblique"

[font.bold_italic]
family = "IosevkaTerm Nerd Font"
style = "Bold Oblique"

[window]
padding.x = 8
padding.y = 8
dynamic_padding = true
decorations = "None"

[keyboard]
bindings = [
{ key = "0", mods = "Control", action = "None" },
{ key = "=", mods = "Control", action = "None" },
{ key = "+", mods = "Control", action = "None" },
{ key = "-", mods = "Control", action = "None" },
{ key = "NumpadAdd", mods = "Control", action = "None" },
{ key = "NumpadSubtract", mods = "Control", action = "None" },
]

[[hints.enabled]]
regex = "(mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"
command = "xdg-open"
post_processing = true

  [hints.enabled.mouse]
  enabled = true
  mods = "Control"
